### ISSUE TITLE
Can't route to IDs with dots

### ISSUE THREAD

**Issue by bibliotechy** [tulibraries/funnel_cake#32]
When we try to go to any of the records in this search https://funnelcake.padigital.org/?q=Equitable+gas+explosion, they all error out. The logs contain something like:
`ActionController::RoutingError (No route matches [GET] "/catalog/pitt:715.L25.CP")`

[Dots are a known issue for rails IDs](https://github.com/rails/rails/issues/31032) ids in routes, though it looks like they can be dealt with by a constraint.

**Comment by cmharlow** [comment]
@nomadicoder this brought down funnel cake dev.
